spring:
  application:
    name: myapp
  config:
    import: optional:configserver:http://config-server:8888
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
