spring:
  profiles:
    active: vault, git
  cloud:
    config:
      server:
        git:
          uri: file://usr/config-repo
          clone-on-start: true
        vault:
          port: 8200
          host: vault
          scheme: http
          authentication: TOKEN
          token: s.ICyYYVARI7pHHHQ3FG6yco93
          kv-version: 2
          backend: kv
server:
  port: 8888

